
project_id = "zjapocdwlxbvyakicotx"

[api]
enabled = true

[auth]
enabled = true

[functions.chat-assistant]
verify_jwt = true

[functions.audit-logger]
verify_jwt = false

[functions.openai-tts]
verify_jwt = false
