// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjapocdwlxbvyakicotx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqYXBvY2R3bHhidnlha2ljb3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NDM0NjcsImV4cCI6MjA2ODExOTQ2N30.JY4SpTh_8pkNQjCvzRGFwb_bJ2dpt2UTkmC9OZAtkl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});